package com.auradev.erp.analytics.dto;

import java.math.BigDecimal;

/**
 * Sales rank data for a single product.
 *
 * @param name    display name of the product
 * @param qty     total units sold in the period
 * @param revenue total revenue generated by this product in the period
 */
public record TopProduct(
        String name,
        long qty,
        BigDecimal revenue
) {}
